guest_search= '//a[text()="Search as a Guest"]'
state_city= '//div[@id="cdk-overlay-0"]//div//input[@aria-label="Enter your location"]'
loc= '//span[@class="mat-option-text"]'
select_state= '//div[@data-cy="location-options.option.0"]'
Continue_button= '//span[text()=" Continue "]'
Search_for_name= '//input[@id="mat-input-2"]'
view_profile= '//span[text()=" View Profile "]'
name_credntial= '//h4[@class="summary-name"]'
contact_no= '//div[@class="contact-phone ng-star-inserted"]'
adress_detail= '//div[@class="location-address ng-star-inserted"]'
xbutton= '//button[@value="No thanks"]'
primary_care='//button[@fxlayoutalign=" center"][text()=" Primary Care "]'
family_practice='//div[text()=" Family Practice "]'
general_practice='//div[text()=" General Practice "]'
internal_medicine='//div[text()=" Internal Medicine "]'
obstetrics_gynecology='//div[text()=" Obstetrics & Gynecology "]'
pediatrics='//div[text()=" Pediatrics "]'
back_button= '//a[@class="back-button"]'
tab='//div[@id="fsrInvite"]'
Search_boxxx = '//input[@data-cy="location-input.selector"]'
